### ISSUE TITLE
Debugibility

### ISSUE THREAD

**Issue by yishangru** [emichael/dslabs#5]
Hi, I am currently a graduate student in Georgia Tech. We are using your system for our distributed computing course this semester. I have finish lab1 - lab3 currently. When I was doing labs, I found it can vary hard to debug about the search tests, especially for the BFS search. I have found a way to log the event sequence for the finished state between several BFS. And I used it by manually input in the vis debug. After I finish lab 4, I might try to add the log function that students can input the event sequences (copy and paste a series of events for BFS state) in the vis debug. Can you give me some suggestions about where to start? Thank you.

**Comment by emichael** [comment]
Hi! Glad to hear you're using the labs.

Instead of manually entering traces in the viz, you can start it programatically by initializing a [`VizClient`](https://github.com/emichael/dslabs/blob/cc10a005279a0d6c225f5c19ee70df9a3c94bf92/framework/tst/dslabs/framework/testing/visualization/VizClient.java#L92) and calling [`run`](https://github.com/emichael/dslabs/blob/cc10a005279a0d6c225f5c19ee70df9a3c94bf92/framework/tst/dslabs/framework/testing/visualization/VizClient.java#L261) on it. Should just take a couple lines that students can paste in wherever they need them.

Alternatively, you can always pause the execution using the IntelliJ debugger and use its state inspector to look at intermediate states.

Hope that helps!
